### ISSUE TITLE
more fine-grained memorymap

### ISSUE THREAD

**Issue by anuejn** [nmigen/nmigen-soc#15]
Hey,
if I understand the intended use of Memorymap correctly, it should hold all information that is needed to write software for the SoC one is generating. 
This works already quite well for me if I only have one "logical register" at one address. However, if I want to have registers which are smaller than 8 bits, and want to have them packed (e.g. when emulating the memory map of an existing peripheral to reuse driver code) I wasn't able to come up with a solution that expresses that using the current Memorymap class in a clean way.

**Comment by whitequark** [comment]
There isn't such a solution. There is an inherent tradeoff between expressibility and complexity in something like the MemoryMap, and no matter how much complexity will go into it, there will always be patterns that are not possible to express. Use a single logical register and work around this in your code.

**Comment by anuejn** [comment]
ok
