### ISSUE TITLE
wishbone.bus: add Arbiter.

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen-soc#3]
<a href="https://github.com/jfng"><img src="https://avatars0.githubusercontent.com/u/5796363?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jfng](https://github.com/jfng)**
_Wednesday Jan 22, 2020 at 14:18 GMT_
_Originally opened as https://github.com/m-labs/nmigen-soc/pull/3_

----

This arbiter should be compatible with all the optional features of `wishbone.Interface`.

The round-robin implementation could perhaps be moved to `nmigen.lib` and imported back here, but that would make nmigen-soc depend on a later revision than nmigen v0.1.

----

_**[jfng](https://github.com/jfng)** included the following code: https://github.com/m-labs/nmigen-soc/pull/3/commits_

**Comment by jfng** [comment]
Superseded by #9.
